{{- if .Values.proxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: proxy-svc
  namespace: {{ $.Values.namespace }}
  labels:
    {{- include "pre-relayer-test.labels" . | nindent 4 }}
spec:
  selector:
    app: pre-relayer-test
  ports:
    - protocol: TCP
      port: {{ $.Values.proxy.port  }}
      targetPort: {{ $.Values.proxy.port  }}
{{ end }}