{{- if .Values.ipfs.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.ipfs.name }} 
  labels:
    {{- include "pre-relayer.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  serviceName: {{ .Values.ipfs.name }}-svc
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.ipfs.name }} 
  template:
    metadata:
      labels:
        app: {{ .Values.ipfs.name }} 
    spec:
      containers:
      - name: ipfs
        image: ipfs/go-ipfs:v0.7.0
        ports:
        - containerPort: {{ .Values.ipfs.dns.port }}
          name: http
          protocol: TCP
        command: ["/bin/sh"]
        args:
          - -c
          - >-
              ipfs config --json API.HTTPHeaders.Access-Control-Allow-Credentials "[\"true\"]" && 
              ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin "[\"*\"]"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/ipfs
          name: ipfs-pre-storage
          subPath: ipfs-data
        livenessProbe:
          tcpSocket:
            port: {{ .Values.ipfs.dns.port }}
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 15
      - name: ipfs-cleaner
        image: ibmcom/cronjob
        ports:
        - containerPort: 5001
        command: ["/bin/sh"]
        args:
          - -c
          - >-
              echo "0 0 * * * rm -rf //data/ipfs/ipfs-data/blocks* && echo 'ipfs cleanup done'" > ./cleanup.sh && 
              chmod +x cleanup.sh && crontab cleanup.sh &&
              /usr/sbin/crond -f -l 8 
        volumeMounts:
        - name: ipfs-pre-storage
          mountPath: /data/ipfs/
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: ipfs-pre-storage
    spec:
      storageClassName: gp2
      volumeMode: Filesystem
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 200Gi
{{ end }}