version: '3.5'

services:
  fetchd:
    # profiles: ["fetchd"]
    build:
      context: ../
      dockerfile: ./docker/fetchd.Dockerfile
    environment:
      FETCHMNEMONIC: "gap bomb bulk border original scare assault pelican resemble found laptop skin gesture height inflict clinic reject giggle hurdle bubble soldier hurt moon hint"

    networks:
      - localnet
  
  ipfs:
    # profiles: ["ipfs"]
    image: "ipfs/go-ipfs:v0.7.0"
    networks:
      - localnet

  admin:
    profiles: ["admin"]
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: pre:latest
    
    container_name: admin
    volumes:
      - ../test_data:/test_data
    entrypoint: >
      python3 apps/admin.py
        --fund
        --ledger-config ${LEDGER_CONFIG}
        --ledger-private-key /test_data/keys/admin_ledger.key
        instantiate-contract
          --threshold 2 
          --proxies fetch1vz7c7h54ve0fcu6gv242xnz0nkegeaszvzs27c,fetch1njgnp7lvhzpgtx7rzt60qu4r2sg8dj0h4ln0y2,fetch10r8j0yf8emj78m3f0j7dddkrmfxpaegkxxan5c
    networks:
      - localnet

  owner:
    profiles: ["owner"]
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: pre:latest
    
    container_name: provider
    volumes:
      - ../test_data:/test_data
      - ${PWD}/:/data/:rw
    #entrypoint: python3 /workdir/apps/owner.py
    entrypoint: >
      python3 apps/owner.py
        --fund
        --ledger-config ${LEDGER_CONFIG}
        --ipfs-config ${IPFS_CONFIG}
        --ledger-private-key /test_data/keys/owner_ledger.key
        --encryption-private-key /test_data/keys/owner_encryption.key
        --threshold 2
    networks:
      - localnet

  proxy:
    profiles: ["proxy"]
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: pre:latest
    
    container_name: proxy
    volumes:
      - ../test_data:/test_data
    #entrypoint: python3 /workdir/apps/proxy.py
    entrypoint: >
      python3 apps/proxy.py
        --fund
        --ledger-config ${LEDGER_CONFIG}
        --ledger-private-key /test_data/keys/proxy_${PROXY_INDEX}_ledger.key
        --encryption-private-key /test_data/keys/proxy_${PROXY_INDEX}_encryption.key
    ports:
      - 9090:9090
    networks:
      - localnet

  reader:
    profiles: ["reader"]
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: pre:latest
    
    container_name: reader
    volumes:
      - ../test_data:/test_data
      - ${PWD}/:/data/:rw
    #entrypoint: python3 /workdir/apps/reader.py
    entrypoint: >
      python3 apps/reader.py
        --fund
        --ledger-config ${LEDGER_CONFIG}
        --ipfs-config ${IPFS_CONFIG}
        --ledger-private-key /test_data/keys/reader_ledger.key
        --encryption-private-key /test_data/keys/reader_encryption.key

    networks:
      - localnet

  tests:
    profiles: ["tests"]
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: pre:latest
    
    container_name: tests
    entrypoint: ./scripts/run_tests.sh
    networks:
      - localnet

networks:
  localnet:
    name: pre-local
    driver: bridge
    ipam:
      driver: default


