# Generated by Django 3.2.10 on 2022-01-12 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_id", models.CharField(max_length=100, unique=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_accesses_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "readers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="data_accesses_granted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "data access",
                "verbose_name_plural": "data accesses",
            },
        ),
    ]
