{{- if .Values.ipfs.enabled }}
apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  namespace: istio-system
  name: {{ .Values.ipfs.dns.cert }}
spec:
  dnsNames:
  - {{ .Values.ipfs.dns.host }}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-dns
  secretName: {{ .Values.ipfs.dns.cert }}
{{ end }}