{{- if .Values.ipfs.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: ipfs-pre-vs-{{ .Values.env }}
  namespace: {{ .Values.namespace }}
spec:
  gateways:
  - ipfs-pre-gw-{{ .Values.env }}
  hosts:
  - {{ .Values.ipfs.dns.host }}
  - {{ .Values.ipfs.dns.extrahost }}
  http:
  - route:
    - destination:
        host: ipfs-pre-svc-{{ .Values.env }}
        port:
          number: {{ .Values.ipfs.dns.port }}
{{ end }}