{{- if .Values.admin.enabled }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: pre-admin
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "pre-relayer.labels" . | nindent 4 }}
spec:
  backendType: secretsManager
  data:
  - key:  {{ .Values.admin.secret.key }}
    name: {{ .Values.admin.secret.name }}
    property: {{ .Values.admin.secret.property }}
    version: {{ .Values.admin.secret.version }}
{{ end }}