{{- if .Values.admin.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pre-relayer
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "pre-relayer.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: gp2
  volumeMode: Filesystem
{{ end }}