
namespace: pre

sha: "3bab254"

admin:
  enabled: true
  name: admin
  image: "gcr.io/fetch-ai-images/colearn-pre-relayer"
  tag: "2a4b916"
  port: 80
  replicas: 1
    
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "200Mi"
      cpu: "200m"

  secret:
    key: colearn-v3/pre-relayer
    name: admin_ledger.key
    property: admin-ledger
    version: latest

ipfs:
  enabled: true
  config:
      addr: ipfs-pre.colearn-v3.fetch-ai.com
      port: 12000
  name: ipfs-pre
  dns:
    host: ipfs-pre.colearn-v3.fetch-ai.com
    target: fetchpub.colearn-v3.fetch-ai.com
    cert: ipfs-pre-cert 
    app: istio-fetchpubig
    istio: ingressgateway
    port: 5001


proxy:
  enabled: true
  image: "gcr.io/fetch-ai-images/colearn-pre-relayer"
  tag: "2a4b916"
  port: 80
  replicas: 5

  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "200Mi"
      cpu: "200m"

  secret:
    key:
      key: colearn-v3/pre-proxy-keys
      name: proxy_ledger
      property: proxy-key
      version: latest
    encryption: 
      key: colearn-v3/pre-proxy
      name: proxy_encryption
      version: latest

legder_config:
  # chain_id: test
  # denom: atestfet
  # node_address: http://fetchd-svc:1317
  # prefix: fetch
  # validator_pk: bbaef7511f275dc15f47436d14d6d3c92d4d01befea073d23d0c2750a46f6cb3
  chain_id: dorado-1
  denom: atestfet
  node_address: grpc-dorado.fetch.ai:443
  prefix: fetch
  faucet_url: https://faucet-dorado.t-v2-london-c.fetch-ai.com
  secure_channel: true