
namespace: pre

sha: "dummy"

admin:
  enabled: true
  name: admin
  image: "gcr.io/fetch-ai-images/colearn-pre-relayer"
  tag: "3bab254"
  port: 80
  replicas: 1
    
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "250Mi"
      cpu: "250m"

  secret:
    key: colearn-v3/pre-relayer
    name: admin_ledger.key
    property: admin-ledger
    version: latest


fetchd:
  enabled: true
  env:
    FETCHMNEMONIC: "gap bomb bulk border original scare assault pelican resemble found laptop skin gesture height inflict clinic reject giggle hurdle bubble soldier hurt moon hint"
  
  image: "gcr.io/fetch-ai-images/colearn-test_fetchd"
  tag: "3bab254"
  port: 1317
  replicas: 1

  resources:
    requests:
      memory: "150Mi"
      cpu: "100m"
    limits:
      memory: "300Mi"
      cpu: "200m"

  istio:
    certname: fetchd-cert
    dnsname: fetchd-demo.colearn-v3.fetch-ai.com
    ingressname: istio-fetchpubig
    target: fetchpub.colearn-v3.fetch-ai.com
    

ipfs:
  config:
    addr: ipfs.sandbox-london-b.fetch-ai.com
    port: 12000


proxy:
  enabled: true
  image: "gcr.io/fetch-ai-images/colearn-pre-relayer"
  tag: "3bab254"
  port: 80
  replicas: 1

  resources:
    requests:
      memory: "150Mi"
      cpu: "100m"
    limits:
      memory: "300Mi"
      cpu: "200m"

  secret:
    key:
      key: colearn-v3/pre-proxy-keys
      name: proxy_ledger.key
      property: proxy-key
      version: latest
    encryption: 
      key: colearn-v3/pre-keys
      name: proxy_encryption.key
      version: latest


legder_config:
  chain_id: test
  denom: atestfet
  node_address: http://fetchd-svc:1317
  prefix: fetch
  validator_pk: bbaef7511f275dc15f47436d14d6d3c92d4d01befea073d23d0c2750a46f6cb3
  # chain_id: capricorn-1
  # denom: atestfet
  # node_address: https://rest-capricorn.fetch.ai:443
  # prefix: fetch
  # faucet_url: https://faucet-capricorn.t-v2-london-c.fetch-ai.com