{{- if .Values.admin.enabled }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: pre-admin
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "pre-relayer-test.labels" . | nindent 4 }}
spec:
  backendType: secretsManager
  data:
  - key:  {{ .Values.admin.creds.key }}
    name: {{ .Values.admin.creds.name }}
    version: {{ .Values.admin.creds.version }}
{{ end }}