{{- if .Values.proxy.enabled }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: pre-proxy
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "pre-relayer.labels" . | nindent 4 }}
spec:
  backendType: secretsManager
  data:
  - key:  {{ .Values.proxy.secret.key.key }}
    name: {{ .Values.proxy.secret.key.name }}
    property: {{ .Values.proxy.secret.key.property }}
    version: {{ .Values.proxy.secret.key.version }}
  - key:  {{ .Values.proxy.secret.encryption.key }}
    name: {{ .Values.proxy.secret.encryption.name }}
    property: {{ .Values.proxy.secret.encryption.property }}
    version: {{ .Values.proxy.secret.encryption.version }}
{{ end }}