{{- if .Values.proxy.enabled }}
{{ $count := .Values.proxy.replicas | int }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: pre-proxy
  namespace: {{ $.Values.namespace }}
  labels:
    {{- include "pre-relayer.labels" . | nindent 4 }}
spec:
  backendType: secretsManager
  data:
{{ range until $count }}
  - {{ if eq $.Values.env "staging" }}
    key:  colearn-v3/pre-proxy-keys
    {{ else }}
    key: colearn-v3/pre-proxy-prod-keys
    {{ end }}
    name: {{ $.Values.proxy.secret.key.name }}-{{ . }}
    property: {{ $.Values.proxy.secret.key.property }}-{{ . }}
    version: {{ $.Values.proxy.secret.key.version }}-{{ . }}
  - {{ if eq $.Values.env "staging"}}
    key:  colearn-v3/pre-proxy-{{ . }}
    {{ else }}
    key: colearn-v3/pre-proxy-prod-{{ . }}
    {{ end }}
    name: {{ $.Values.proxy.secret.encryption.name }}-{{ . }}
    version: {{ $.Values.proxy.secret.encryption.version }}-{{ . }}
{{ end }}
{{ end }}