{{- if .Values.proxy.enabled }}
{{ $helmlabels := include "pre-relayer.labels" . | nindent 4 }}
{{ $count := .Values.proxy.replicas | int }}
{{ range until $count }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-{{ . }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9090'
    prometheus.io/path: '/metrics'
  labels:
    app: pre-relayer-proxy-{{ . }}
    {{- $helmlabels }}
  namespace: {{ $.Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pre-relayer-proxy-{{ . }}
  template:
    metadata:
      labels:
        app: pre-relayer-proxy-{{ . }}
    spec:
      containers:
        - name: proxy
          image: {{ $.Values.proxy.image }}:{{ $.Values.proxy.tag }}
          resources:
            {{- toYaml $.Values.proxy.resources | nindent 12 }}
          ports:
            - containerPort: {{ $.Values.proxy.port  }}
          env:
            - name: LEDGER_CONFIG
              value: "/configs/ledger_config.yaml"
            - name: PROXY_LEDGER
              value: "/keys/proxy_ledger-{{ . }}.key"
            - name: PROXY_ENCRYPTION
              value: "/keys/proxy_encryption{{ . }}.key"
          volumeMounts:
            - name: config-volume
              mountPath: /configs/ledger_config.yaml
              subPath: ledger_config.yaml
            - name: proxy-key-volume
              mountPath: /keys/proxy_ledger-{{ . }}.key
              subPath: proxy_ledger-{{ . }}
            - name: proxy-key-volume
              mountPath: /keys/proxy_encryption{{ . }}.key
              subPath: proxy_encryption-{{ . }}
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - ./scripts/liveness.sh
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 10
          command: ["/bin/sh"]
          args:
            - -c
            - >-
                export CONT_ADDR=$( curl https://pre-relayer.s3.us-west-2.amazonaws.com/contract/latest.json | jq -r .contract_address)  && 
                python3 apps/proxy.py --fund --contract-address ${CONT_ADDR} --ledger-config ${LEDGER_CONFIG} --ledger-private-key ${PROXY_LEDGER} --encryption-private-key ${PROXY_ENCRYPTION} run 
      volumes:
        - name: config-volume
          configMap:
            name: relayer-config
        - name: proxy-key-volume
          secret:
            secretName: pre-proxy
      restartPolicy: "Always"
---
{{ end }}
{{ end }}