namespace: ipfs
env: prod

ipfs:
  enabled: true
  image: gcr.io/fetch-ai-images/ipfs-pre-prod:0.9
  config:
      addr: ipfs-pre-prod.colearn-v3.fetch-ai.com
      port: 12000
  name: ipfs-pre
  dns:
    host: ipfs-pre-prod.colearn-v3.fetch-ai.com
    extrahost: ipfs.fetch-ai.com
    target: fetchpub.colearn-v3.fetch-ai.com
    cert: ipfs-pre-prod-cert 
    app: istio-fetchpubig
    istio: ingressgateway
    port: 5001