name: Cosmwasm Rust Contract Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  CONTRACT_ROOT: contract/proxy_reencryption/

jobs:
  code_quality:
    if: ${{ false }}  # disable for now

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Rust environment
      run: |
        rustup target add wasm32-unknown-unknown
    - name: Build
      run: |
        cd ${CONTRACT_ROOT}
        RUSTFLAGS='-C link-arg=-s --deny warnings' cargo wasm --verbose
    - name: Style checks
      run: |
        cd ${CONTRACT_ROOT}
        cargo fmt --all -- --check
    - name: Linter checks
      run: |
        cd ${CONTRACT_ROOT}
        cargo clippy -- -D warnings
  
  unit_tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Rust environment
      run: |
        rustup target add wasm32-unknown-unknown
    - name: Build
      run: |
        cd ${CONTRACT_ROOT}
        RUSTFLAGS='-C link-arg=-s --deny warnings' cargo wasm --verbose
    - name: Run tests
      run: |
        cd ${CONTRACT_ROOT}
        cargo test --verbose
  
  code_coverage:
    if: ${{ false }}  # disable for now

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Rust environment
      run: |
        rustup target add wasm32-unknown-unknown
    - name: Install cargo-make
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: --debug cargo-make
    - name: Compile tests
      run: |
        cd ${CONTRACT_ROOT}
        RUSTFLAGS='-C link-arg=-s --deny warnings -C link-dead-code' cargo wasm --verbose
        RUSTFLAGS='-C link-dead-code' cargo test --no-run
    - name: Run Coverage
      run: cargo make coverage-kcov
      # TODO(LR) https://fetchai.atlassian.net/browse/COLE-1560
      #   upload coverage information to codecov and check if declined
      working-directory: ${CONTRACT_ROOT}