name: python

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    continue-on-error: False
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
       - uses: actions/checkout@v1
       - uses: actions/setup-python@master
         with:
           python-version: 3.9
       - name: Install dependencies
         run: |
           wget -O ./go-ipfs.tar.gz https://dist.ipfs.io/go-ipfs/v0.6.0/go-ipfs_v0.6.0_linux-amd64.tar.gz
           tar xvfz go-ipfs.tar.gz
           sudo mv go-ipfs/ipfs /usr/local/bin/ipfs
           ipfs init 
           pip install tox
       - name: build contract
         run: cd contract && ./build_in_docker.sh
       - name: copy of the contract into python dir
         run: pip install .
       - name: Run tests
         run: tox -e py39
