version: '3'

services:

  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  # For local run purposes
  ipfs:
    image: "ipfs/go-ipfs:v0.7.0"
    ports:
      - "5001:5001"
  
  ledger:
    image: fetchai/fetchd:0.9.0
    logging:
      driver: "none"
    volumes:
      - .:/ledger
    entrypoint: ["sh", "/ledger/ledger_entrypoint.sh"]
    ports:
      - "1317:1317"
      - "26657:26657"

  backend:
    build: 
      context: ../
      dockerfile: ./web/backend/Dockerfile
    working_dir: /backend
    command: >
      bash -c "
      python manage.py collectstatic --noinput
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./backend:/backend
      - static:/backend/static
      - uploads:/backend/uploads
    expose:
      - "8000"
    depends_on:
      - db
      - ledger
      - ipfs

  frontend:
    build: ./frontend
    working_dir: /frontend
    volumes:
      - './frontend:/frontend'
      - '/frontend/node_modules'
    command: bash -c "npm start"
    stdin_open: true
    ports:
      - 3000:3000
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true

  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - backend
    volumes:
      - static:/backend/static
      - uploads:/backend/uploads

volumes:
  static:
  uploads: